#!/usr/bin/env -S uv run --script
#MISE description="List contacts in the XMPP roster"
# /// script
# dependencies = ["slixmpp>=1.8"]
# ///

import asyncio
import os
import sys

sys.path.insert(0, os.environ["MISE_CONFIG_ROOT"] + "/lib")
from xmpp import list_contacts

jid = os.environ.get("SMS_JID", "")
password = os.environ.get("SMS_PASSWORD", "")

if not jid or not password:
    print("SMS_JID and SMS_PASSWORD must be set")
    sys.exit(1)

contacts = asyncio.run(list_contacts(jid, password))

if not contacts:
    print("No contacts")
else:
    for c in contacts:
        sub = c["subscription"]
        name = f' ({c["name"]})' if c["name"] else ""
        print(f"{c['jid']}{name}  [{sub}]")
